# Site settings
title: Arkopal Das
name: Arkopal Das
email: arkopaldas27@gmail.com
description: >-
  Computer Science PhD student at Indian Association for the Cultivation of Science,
  with interests in algorithms, mathematical art, and application development.
baseurl: "https://arkopaldas.github.io/MyPage/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol, e.g. http://example.com

# Social profiles
github: https://github.com/arkopaldas # Update this
linkedin: https://linkedin.com/in/arkopal-das-800630225 # Update this
google_scholar: # Add if available
twitter: # Add if available

# Academic info
position: Integrated PhD Student
department: Computer Science
institution: Indian Association for the Cultivation of Science

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - README.md
